#!/usr/bin/env bash 
#Script which display the content of /etc/passwd in a funny story format
FILE="/etc/passwd"
while IFS=":" read -r username password userid groupid homedir cmdshell uinfo
do echo "The user $username is part of the $groupid gang, lives in $homedir and rides $cmdshell.$userid's place is protected by the passcode $password, more info about the user here: $uinfo"
done < $FILE
