#!/usr/bin/env bash 
# script which displays "Best School" 10 times, but "bad luck" for the 4th , "good luck" for the 8th
i="1"
while [ $i -le 10 ]
do 
	if [ $i -eq 4 ]; then 
		echo "bad luck"
	elif [ $i -eq 8 ]; then 
		echo "good luck"
	else
		echo "Best School"
	fi
		(( i++ ))
done 
 
