#!/usr/bin/env bash 
#this script is a headache 

rm_file_exit()
{
	rm -f /var/run/myscript.pid;
	exit
}
trap "echo 'Y U no love me ?!'" SIGINT
trap " echo 'I hate the kill command'; rm_file_exit " SIGTERM
trap "rm_file_exit" SIGQUIT



echo $$ >> /var/run/myscript.pid

while true :
do 
	echo 'To infinity and beyond'
	sleep 2
done
