#!/usr/bin/env bash 
#crazy init script

arg="$1"
File="/var/run/my_process.pid"

starting()
{
	./manage_my_process &
	echo "$!" > "$File"
}

killing()
{
	sudo pkill -f "manage_my_process"
	rm "$File"
}


case "$arg" in

   start) 
	echo "manage_my_process started"
	starting ;;
   stop) 
	echo "manage_my_process stopped"
	killing ;;

   restart) echo "manage_my_process restarted"
	   killing
   	   starting ;;

   *) echo "Usage: manage_my_process {start|stop|restart}"
      ;;
esac
