#!/usr/bin/env bash 
# Script display > To infinity and beyond < indefinitely,  with a sleep between each iteration, when the command kill occurs, it ignores it and print a message instead with the trap command 

pikachu()
{
	echo 'I am invincible !!!' 
      }
trap pikachu SIGTERM 

while true 
	do 
		echo 'To infinity and beyond'
		sleep 2
	done
