#!/usr/bin/env bash 
# Script display > To infinity and beyond < indefinitely,  with a sleep between each iteration, when the command kill occurs, it ignores it and print a message instead with the trap command 


trap "echo 'I am invincible !!!' " SIGTERM 

while true 
	do 
		echo 'To infinity and beyond'
		sleep 2
	done
